package servlets;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class ParagraphGenerateForm
 */
@WebServlet("/ParagraphGenerator")
public class ParagraphGenerateForm extends HttpServlet {
	private static final long serialVersionUID = 1L;

    /**
     * @see HttpServlet#HttpServlet()
     */
    public ParagraphGenerateForm() {
        super();
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		PrintWriter out = response.getWriter();
		response.setContentType("text/html");

		out.append("<!DOCTYPE html> <html> <header> </header> <body> ");
		out.append("<h1> Paragraph generator  </h1>");
		out.append("<p> This page allows generating a page containing as many html paragraphs as requested via the following form: To do so it makes use of RequestDispatcher.include()</p>");
		out.append(
			  "<form action='' method='POST'>"
			+ "<label for='numPars'> Number of paragraphs: </label>"
			+ "<input type='number' name='numPars' id='numPars' placeholder='# Here'/>"
			+ "<label for='content'> Content: </label>"
			+ "<input type='text' name='pText' id='content' placeholder='paragraph content'/>"
			+ "<button > Generate!</button>"
			+ "</form>"
		);
		out.append("</body></html>");

		out.flush();
		out.close();
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		PrintWriter out = response.getWriter();
		response.setContentType("text/html");

		out.append("<!DOCTYPE html> <html> <header> </header> <body> ");

		// get number of paragraphs
		int pending = Integer.parseInt(request.getParameter("numPars"));

		out.format("<h1>Generated %d paragraphs</h1>", pending);

		for (; pending > 0; pending--) {
			// add html generated by ParGen servlet
			getServletContext().getRequestDispatcher("/utils/ParGen").include(request, response);
		}

		out.flush();
		out.close();
	}

}
